spring.application.name=SB-DMS-SERVICE
#Embedded TomCat port number using server.port property
server.port = 2222

#Database connection properties
spring.datasource.url=jdbc:mysql://localhost:3306/training
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Application Properties
dms.save.success = "SUCCESS : Department Object Saved"
dms.update.success = "SUCCESS : Department Object Updated"
dms.delete.success= "SUCCESS: Department Object Deleted"

#application error properties
dms.invalid.employee-details="FAILED: Invalid Department Details";
dms.invalid.employee-notfound="FAILED: Department Not Found";
dms.db.failed = "FAILED : DB Error "
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
