spring.application.name=SB-SMS-SERVICE

#embeded tomcat port number
server.port= 3333

#database connection properties
spring.datasource.url=jdbc:mysql://localhost:3306/training
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#application properties
sms.save.success="SUCCESS : Supplier Object Saved"
sms.update.success="SUCESS : Supplier Object Updated"
sms.delete.success="SUCESS : Supplier Object Deleted"

#application error properties
sms.invalid.supplier-details="FAILED : Invalid Supplier Details";
sms.invalid.supplier-notfound="FAILED : Supplier Not Found";

sms.db.failed="FAILED : DB Error"