spring.application.name=SB-EMS
#Embedded TomCat port number using server.port property
server.port = 1243

#Database connection properties
spring.datasource.url=jdbc:mysql://localhost:3306/training
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Application Properties
ems.save.success = "SUCCESS : Employee Object Saved"
ems.db.failed = "FAILED : DB Error "

ems.update.success = "SUCCESS : Employee Object Updated"
ems.delete.success= "SUCCESS: Employee Object Deleted"