spring.application.name=SB-PMS

#Embedded TomCat port number using server.port property
server.port = 1205

#Database connection properties
spring.datasource.url=jdbc:mysql://localhost:3306/training
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

pms.save.success=Product Saved Successfully
pms.update.success=Product Updated Successfully
pms.delete.success=Product Deleted Successfully
pms.db.failed=Database Operation Failed