spring.application.name=SB-ARS

server.port=1515

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/airline_reservation_system_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

user.save.success=User Registered Successfully
user.update.success=User Updated Successfully
user.delete.success=User Deleted Successfully
user.invalid.notfound=User Not Found
user.invalid.email=Email Already Exists
user.invalid.login=Invalid Email or Password
user.invalid.role=Invalid User Role
user.invalid.details=Invalid User Details
user.invalid.admin=Only one Admin is allowed

airport.save.success=Airport Saved Successfully
airport.update.success=Airport Updated Successfully
airport.delete.success=Airport Deleted Successfully
airport.invalid.notfound=Airport Not Found
airport.invalid.details=Invalid Airport Details

airplane.save.success=Airplane Saved Successfully
airplane.update.success=Airplane Updated Successfully
airplane.delete.success=Airplane Deleted Successfully
airplane.invalid.notfound=Airplane Not Found
airplane.invalid.details=Invalid Airplane Details


flight.save.success=Flight Saved Successfully
flight.update.success=Flight Updated Successfully
flight.delete.success=Flight Deleted Successfully
flight.invalid.notfound=Flight Not Found
flight.invalid.details=Invalid Flight Details

wallet.save.success=Wallet Created Successfully
wallet.update.success=Wallet Updated Successfully
wallet.delete.success=Wallet Deleted Successfully
wallet.invalid.notfound=Wallet Not Found
wallet.invalid.exists=Wallet Already Exists
wallet.invalid.details=Invalid Wallet Details
wallet.insufficient.balance=Insufficient Wallet Balance
wallet.addmoney.success=Money Added Successfully

booking.save.success=Booking Saved Successfully
booking.update.success=Booking Updated Successfully
booking.delete.success=Booking Deleted Successfully
booking.invalid.notfound=Booking Not Found
booking.invalid.details=Invalid Booking Details

passenger.save.success=Passenger Saved Successfully
passenger.update.success=Passenger Updated Successfully
passenger.delete.success=Passenger Deleted Successfully
passenger.invalid.notfound=Passenger Not Found
passenger.invalid.details=Invalid Passenger Details

waiting.save.success=Waiting List Saved Successfully
waiting.update.success=Waiting List Updated Successfully
waiting.delete.success=Waiting List Deleted Successfully
waiting.invalid.notfound=Waiting List Not Found
waiting.invalid.details=Invalid Waiting List Details


admin.save.success=Saved Successfully
admin.update.success=Updated Successfully
admin.delete.success=Deleted Successfully
admin.invalid.notfound=Record Not Found
admin.invalid.details=Invalid Details

invalid.details=Invalid Details